version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: adote_facil_cms
      POSTGRES_USER: jpcosta
      POSTGRES_PASSWORD: 101193
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payload:
    build:
      context: ./adote-facil
      dockerfile: Dockerfile
    environment:
      - DATABASE_URI=postgresql://jpcosta:101193@postgres:5432/adote_facil_cms
      - PAYLOAD_SECRET=sua_chave_secreta
    ports:
      - "3001:3000"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URI=postgresql://jpcosta:101193@postgres:5432/adote_facil_cms
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
      - NEXT_PUBLIC_CMS_URL=http://payload:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - payload

volumes:
  pgdata:
